### ISSUE TITLE
Data delay?

### ISSUE THREAD

**Issue by mbodge** [backtrackbaba/covid-api#1]
Hi there, first of all thank you for making this!

You said you have the data pulling 3 times a day...I haven't seen the numbers for total confirmed cases change since I looked at the site early this morning. They don't match up with the John Hopkins dashboard. Has the data just not updated yet?

m

**Comment by backtrackbaba** [comment]
Hi @mbodge ,
As mentioned in the README, the data we use is from this repository which updates thrice a day - [pomber](https://github.com/pomber/covid19/) which in turn uses the data from [John Hopkins](https://github.com/CSSEGISandData/COVID-19) 

Now, pomber, fetches the new data at "At minute 15 past hour 5, 13, and 21." every day as described in their [Github Action file](https://github.com/pomber/covid19/blob/master/.github/workflows/main.yml). We fetch the new data, keeping a 5 min buffer.

Also, I've manually triggered an update a few minutes back. Could you check the data again if it matches up and if not then share the endpoint you are trying to access?

**Comment by backtrackbaba** [comment]
Johns Hopkins is going to change the pattern of the data a bit as mentioned in this [Issue](https://github.com/CSSEGISandData/COVID-19/issues/1250).

I'm waiting for that change, and in the meantime, I'm trying to get a form of pomber's code up and running with a higher frequency of updates. This should be up hopefully by tomorrow.

**Comment by mbodge** [comment]
Thanks for the quick response!

I'm seeing on the JH dashboard a total cases of 372,563. 

`https://covidapi.info/api/v1/global`

returns 335,955

**Comment by backtrackbaba** [comment]
I'm currently dependant on Pomber's code which for some reason hasn't updated in the last 16 hours. It should have ideally updated at 21:00 UTC which is approx 20 mins back.

It's past midnight in my timezone, let me see if I can get an updated result in some time. Otherwise, it'll surely be up in say  at the most 12 hours

**Comment by backtrackbaba** [comment]
Hey @mbodge closing this issue for now,  please feel free to open another issue!
