### ISSUE TITLE
No updates

### ISSUE THREAD

**Issue by r0man1337** [backtrackbaba/covid-api#10]
Autoupdate is broken? Last update was at 2020-03-26

**Comment by backtrackbaba** [comment]
I'm checking the same. Give me a minute, I'll get back to you

**Comment by backtrackbaba** [comment]
Hi @r0man1337, I've checked it out. Everything seems to be fine. The data of [JHU](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data) hasn't been updated yet. If you are looking for the records for today, i.e 27th March, that would be updated at the end of the day. 
Once they update, it would be fetched. Their last update was around 17 hours ago

**Comment by backtrackbaba** [comment]
@r0man1337 Closing this issue as data was updated a few hours ago
