### ISSUE TITLE
Data delayed?

### ISSUE THREAD

**Issue by Lander2003** [backtrackbaba/covid-api#11]
I can only access data from 2 days ago, how can I get the latest data? Do I need to update something?

**Comment by backtrackbaba** [comment]
27th March is the last dat that I can see. Ideally, you should be getting the same. Could you try using [this endpoint](https://covidapi.info/api/v1/global) to see what date you get?

**Comment by Lander2003** [comment]
Yeah that's what I meant, Is there a way to get live data from today?

**Comment by backtrackbaba** [comment]
No, our data gets updated when JHU updates [theirs](https://github.com/CSSEGISandData/COVID-19). There are a few other sources but I couldn't find any as reliable as JHU
