### ISSUE TITLE
Written "The datasets are updated thrice a day" but not yet updated almost 12 hour passed

### ISSUE THREAD

**Issue by khadkasimon** [backtrackbaba/covid-api#14]
Written "The datasets are updated thrice a day" but not yet updated almost 12 hour passed

**Comment by backtrackbaba** [comment]
Hi @khadkasimon,

Sorry for the inconvenience. JHU isn't updating the data as frequently as it was until a few days back. 

I've written an explanation to a similar query to Issue #12 and would refer you to the same.

Do let me know if you have a plan of action or suggestion in mind.

**Comment by backtrackbaba** [comment]
Closing the issue. Let me know if you face any other issue
