### ISSUE TITLE
Global timeseries API is throwing Internal Server Error 500

### ISSUE THREAD

**Issue by vineetisforu** [backtrackbaba/covid-api#15]
![image](https://user-images.githubusercontent.com/9901025/78104407-cdd5ec80-740c-11ea-97e4-44da7c658ea8.png)

**Comment by maziyarpanahi** [comment]
Yes, same for me

**Comment by maziyarpanahi** [comment]
Other APIs are fine, I am guessing there is a data format, etc. with this one today (maybe after the last update)

**Comment by backtrackbaba** [comment]
Hey, @vineetisforu @maziyarpanahi Looking into it

**Comment by backtrackbaba** [comment]
Just like what @maziyarpanahi said. Fixed it right away.

**Comment by maziyarpanahi** [comment]
@backtrackbaba you rock! Thank you 🙏
