### ISSUE TITLE
What timezone are the responses in?

### ISSUE THREAD

**Issue by SammyIsra** [backtrackbaba/covid-api#17]
I am trying to display some info on a website received from this endpoint, something along the lines of "40,000 cases as of 04/11/2020" but that date can differ quite a bit depending on where in the world the browser is if I don't know the timezone of the response. 

If no timezone information is provided, ISO 8601 formatted dates are to be represented as _local_ time [Info here](https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators)

Thank you for the help!

**Comment by backtrackbaba** [comment]
Hi @SammyIsra,

The timestamps are in UTC(00:00) as the upstream data provider, [JHU](https://github.com/CSSEGISandData/COVID-19) updates the data around 00:00 UTC every night. 

Let me know if you have any suggestions or queries.

**Comment by SammyIsra** [comment]
Fantastic, thank you!
