### ISSUE TITLE
Data for 2020-04-07

### ISSUE THREAD

**Issue by nizarGannouni** [backtrackbaba/covid-api#19]
Hello I appreciate this great work.
Why there is no data for 2020-04-17?
best regards.

**Comment by SamuelCody** [comment]
I also appreciate for this great work. The last time the api updated was two days ago. Pls what's wrong? 

Great job

**Comment by backtrackbaba** [comment]
The updation script failed. I didn't take a look at the notification today. Sorry for the trouble. I've updated it right now.

@nizarGannouni  @SamuelCody  Thank you for pointing it out

**Comment by backtrackbaba** [comment]
Let me know if you face any issues in the data. Everything should be working fine in 2-3 mins

**Comment by nizarGannouni** [comment]
it's updated now,
thanks for the quick intervention.
best regards.

**Comment by SamuelCody** [comment]
Thanks a lot. It's updated.

**Comment by SamuelCody** [comment]
Hello, pls what about the data for 2020/04/20. Can you pls check if the update script failed again?

**Comment by backtrackbaba** [comment]
Sorry for the trouble, same issue as the other day. I had a separate service that I used scheduling tasks in my personal projects which seems to be acting a little weird.

I've moved this updating script to cron to avoid this issue in the future.

**Comment by nizarGannouni** [comment]
Thanks a lot.

**Comment by SamuelCody** [comment]
Ok. Thanks
