### ISSUE TITLE
Internal Server Error on global timeseries request

### ISSUE THREAD

**Issue by multit** [backtrackbaba/covid-api#21]
I got a 500 internal server error on a global timeseries request.
It's happening also with the example request from the documentation page — https://covidapi.info/api/v1/global/timeseries/2020-03-10/2020-03-19.
There's a way to fix it?

**Comment by backtrackbaba** [comment]
Thank you for notifying, have fixed it

**Comment by multit** [comment]
It's ok now, thank you for your good job
