### ISSUE TITLE
Service Down?

### ISSUE THREAD

**Issue by cervaens** [backtrackbaba/covid-api#26]
Hi, thanks for the great work here.
It seems the service is down. Is it being discontinued?
Thanks,
Nuno

**Comment by backtrackbaba** [comment]
Hey @cervaens the server is temporarily down due to non-payment of resources. Working on getting it back up ASAP

**Comment by cervaens** [comment]
@backtrackbaba  thanks for your prompt reply! :)

**Comment by backtrackbaba** [comment]
@cervaens It's back up. Thank you for reporting the issue!

**Comment by cervaens** [comment]
@backtrackbaba Many thanks again for your prompt reply. Nuno
