### ISSUE TITLE
Recovered stats coming back as 0

### ISSUE THREAD

**Issue by eruecco87** [backtrackbaba/covid-api#3]
All dates I've tried have returned a 0 value for recovered cases

https://covidapi.info/api/v1/global/2020-03-1
https://covidapi.info/api/v1/global/2020-03-2
https://covidapi.info/api/v1/global/2020-03-3
https://covidapi.info/api/v1/global/2020-03-3

**Comment by backtrackbaba** [comment]
Hi, [John Hopkins University](https://github.com/CSSEGISandData/COVID-19) has decided to drop the recovered data as there aren't credible sources to report them.

Please refer to this [issue](https://github.com/CSSEGISandData/COVID-19/issues/1250)

**Comment by backtrackbaba** [comment]
I'm working on enabling a workaround to recover the data until the 22nd of March. It'll be up by tomorrow. 

In the meantime, I wanted to know, are you using our endpoints? Is there any feedback or suggestions that you would like to pass on?

**Comment by eruecco87** [comment]
Right now I'm just trying to develop a dashboard for my local region but I've just started.

So far this has been the most complete and flexible resource I could find about the COVID-19 world stats.

I'm trying to figure out if there's another API out there to pull breaking news from around the world about the virus

**Comment by backtrackbaba** [comment]
Thanks for the feedback @eruecco87! Glad to know you liked it.

As for the latest news, check out if you could use any of the Twitter hashtags. One of the dashboards was using streaming data from a hashtag. If I find that site, I'll link it here.

 BTW, I would be adding endpoints to fetch top countries sorted as per death and confirmed counts. If there is any other endpoint which would be helpful let me know, I'll put it out

**Comment by eruecco87** [comment]
Twitter is an absolutely fantastic idea!

**Comment by backtrackbaba** [comment]
Let me know once your dashboard is up. I'll be adding the links in the README about the projects using this data.

Hack on!

**Comment by Lander2003** [comment]
Hello I made a web app using your API to display data about the covid19!

**Comment by backtrackbaba** [comment]
Hi @eruecco87 , just a quick update JHU has enabled the recovered count again. Just the thing is in some cases, in the latest record, it might be null as they update the day's recovered tally at the end of the day.

Let me know if you face any issues
