### ISSUE TITLE
Historic data is 1 week behind

### ISSUE THREAD

**Issue by pseudocoder10** [backtrackbaba/covid-api#30]
Hello, thanks for your amazing API.
 
The historic data for any country seems to be one week behind real time, for eg for [India](https://covidapi.info/api/v1/country/IND) the api as of today (22nd April) shows 17th April as the latest date and the same is true for any other country

**Comment by Mativve** [comment]
Hello

I found this API today and I have the same issue.

Today we have 2021-05-10 but last data in API is 2021-05-06.

In my case I use this countries: DEU, POL, CZE

This problem is with API or I do something wrong?

**Comment by backtrackbaba** [comment]
Hey @Mativve, the issue was with the API. Sorry for the late response. The issue has been resolved

There's a sync job that fails at times. I'm planning to move this to a better server to improve the reliability.
