### ISSUE TITLE
Will you guys bring back the recovered category? 

### ISSUE THREAD

**Issue by Lander2003** [backtrackbaba/covid-api#5]
Im making a tracker and it seems that the recovered category doesnt work, it only returns 0. Will you guys bring this back?

**Comment by backtrackbaba** [comment]
Hi @Lander2003 , this project internally uses the data provided by [Johns Hopkins University (JHU)](https://github.com/CSSEGISandData/COVID-19) which is a very credible source. JHU, has decided to drop the recovered stats starting 22nd March as mentioned in this [issue](https://github.com/CSSEGISandData/COVID-19/issues/1250).  This was dropped by them as there wasn't any proper way to get that data.

We are updating our scripts to fetch the historic data of recovered until 22nd March but anything after 22nd March would either not be updated or would be kept as 0. This is a call that we need to take as a community. 

Let me know your views. Looking forward to seeing your tracker

**Comment by timday** [comment]
If you were using the recovered numbers to compute an "active cases" number, here's a crude work-round: https://github.com/CSSEGISandData/COVID-19/issues/1250#issuecomment-603255860

**Comment by backtrackbaba** [comment]
Thanks @timday Will check it out. We might have to modify it to avoid numpy . Please feel free to raise a PR.

**Comment by backtrackbaba** [comment]
Hi @Lander2003 , JHU has enabled the recovery count. Just the thing is in some cases, in the latest record, it might be null as they update the day's recovered tally at the end of the day.

Let me know if you face any issues!

**Comment by Lander2003** [comment]
That is great news, as of now things are going great the API is amazing. I am happy to show you my tracker once I finish all the features!
