### ISSUE TITLE
I Updated Postman

### ISSUE THREAD

**Issue by genecyber** [backtrackbaba/covid-api#6]
I can't do a PR on the postman collection so I just published my changes here: https://documenter.getpostman.com/view/13008/SzYUXfng?version=latest#e748420e-013a-4b57-bb67-54499d7df5fa

I parameterized each url parameter so they show up correctly in postman as a parameter like so:
![image](https://user-images.githubusercontent.com/179362/77567773-066e4700-6e9e-11ea-9959-28cf814d3433.png)

**Comment by genecyber** [comment]
Here is a link to the raw collection as well: https://www.getpostman.com/collections/2871c12be082524a2dce

**Comment by backtrackbaba** [comment]
Hey, @genecyber  Thank you for the collection. Let me add the collection here so you could raise a PR on the same.

Also, I've just updated the collection with two more endpoints, could you take of them as well?

**Comment by backtrackbaba** [comment]
@genecyber I've added the postman collection [here](https://github.com/backtrackbaba/covid-api/tree/master/data/collections)

**Comment by genecyber** [comment]
Issued a PR to my updated collection (parameterized) along with an iso country list in array format
